service: crypto-advice-tweets

plugins:
  - serverless-python-requirements
  - serverless-prune-plugin

custom:
  pythonRequirements:
    dockerizePip: non-linux
    zip: true
    slim: true
    useDownloadCache: true
    useStaticCache: true
  prune:
    automatic: true
    number: 3

provider:
  name: aws
  region: eu-west-1
  runtime: python3.7
  environment:
    CONSUMER_KEY: ${ssm:/dev/crypto/consumer_key}
    CONSUMER_SECRET: ${ssm:/dev/crypto/consumer_secret}
    ACCESS_TOKEN: ${ssm:/dev/crypto/access_token}
    ACCESS_TOKEN_SECRET: ${ssm:/dev/crypto/access_token_secret}
    PG_USER: ${ssm:/dev/crypto/pg_user}
    PG_PASS: ${ssm:/dev/crypto/pg_pass}
    PG_HOST: ${ssm:/dev/crypto/pg_host}
    PG_PORT: ${ssm:/dev/crypto/pg_port}
    PG_DB: ${ssm:/dev/crypto/pg_db}

functions:
  cron:
    memorySize: 256
    timeout: 60
    handler: handler.run
    events:
      - schedule: cron(0/3 * * * ? *)
