service: crypto-advice-tweets

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux
    zip: true
    slim: true
    useDownloadCache: true
    useStaticCache: true

provider:
  name: aws
  region: eu-west-1
  runtime: python3.7

functions:
  cron:
    memorySize: 256
    timeout: 60
    handler: handler.run
    events:
      - schedule: cron(0/5 * * * ? *)
